-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출을 조회
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE*O.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER O 
LEFT JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE TO_CHAR(O.PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY 3 DESC, 1